### PR TITLE
fix for initializing the store as undefined

### PR DESCRIPTION
**Pull request by ghost**
This patch includes a fix and test case for when a store is first initialized and the `ev.target.result` is `undefined`. I also had to add an `opts.name` parameter to reproduce this test case, but I think this is a good thing for the API to have anyway.

### CODE REVIEW

**Comment by santiagogil** [comment]
Great thanks :)

**Comment by santiagogil** [comment]
@feross has admin rights for npm.
I'm still on the road.

**Comment by feross** [comment]
@santiagogil Cool, published 0.1.1. Btw, can you add me to the github repo so I can push the commit that changes the version in `package.json`? Cheers!

**Comment by santiagogil** [comment]
@feross : Just added you as admin. Open Open Source ;)
Huge thanks.

**Pull request merged**
